volumes:
  caddy_data:
  caddy_config:

services:
  app:
    restart: unless-stopped
    build:
      context: .
      target: prod
      dockerfile: Dockerfile
    container_name: app
    expose:
      - ${PORT}
    environment:
      - MONGODB_URI=${MONGODB_URI}

  caddy:
    restart: unless-stopped
    build:
      context: ./caddy
      dockerfile: Dockerfile
    container_name: caddy
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    environment:
      - PORT=${PORT}
      - DOMAIN_NAME=${DOMAIN_NAME}
